# Generated by Django 5.1.1 on 2024-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
    ]
